namespace Nao.Assistant

/// Application localization (i18n).
///
/// All user-facing UI strings funnel through a single `Strings` record so the app can be
/// translated by adding another language table — no view code changes required. Today only
/// English ships; the infrastructure (a `Language` union, a per-language table, and a
/// global current-language switch read fresh on every render) is ready to extend.
///
/// Usage in views: `let t = Localization.current ()` then `t.Send`, `t.Settings`, etc.
module Localization =

    /// Supported UI languages. Add a case here, a table below, and wire `tableFor`.
    type Language =
        | English
        | Chinese
        | Hindi
        | Spanish
        | French
        | Arabic
        | Portuguese
        | Russian
        | Japanese
        | German

    /// Every localizable string in the app. Group by area for readability.
    type Strings =
        { // Shell / navigation
          NewSessionTooltip: string
          WorkshopTooltip: string
          SettingsTooltip: string
          NoSessionSelected: string
          // Session view
          ComposerPlaceholder: string
          Send: string
          Attach: string
          StartConversation: string
          LoadingHistory: string
          Working: string
          ThanksFeedback: string
          // Settings view
          SettingsTitle: string
          SettingsSubtitle: string
          Appearance: string
          Theme: string
          ThemeDark: string
          ThemeLight: string
          Language: string
          Provider: string
          Orchestrator: string
          Workspace: string
          Save: string
          Close: string
          // Settings detail (provider / orchestrator / workspace)
          LlmProvider: string
          FieldType: string
          FieldEndpoint: string
          FieldModel: string
          MaxRounds: string
          Temperature: string
          ContextWindow: string
          SystemPrompt: string
          PathLabel: string
          WorkspaceWatermark: string
          WorkspaceHint: string
          // Settings detail (server / connection)
          Server: string
          ServerMode: string
          ServerLocal: string
          ServerRemote: string
          ServerRemoteUrl: string
          ServerEmail: string
          ServerSendLink: string
          ServerSignOut: string
          ServerSignedInAs: string
          ServerNotSignedIn: string
          ServerHint: string
          // Settings — permissions
          Permissions: string
          PermissionsEnabled: string
          PermissionsOn: string
          PermissionsOff: string
          PermissionsAllowedDomains: string
          PermissionsAllowedPaths: string
          PermissionsHint: string
          // Live permission approval prompt (pushed over the WebSocket)
          PermissionPromptTitle: string
          PermissionAllowOnce: string
          PermissionAllowSession: string
          PermissionAllowGlobal: string
          PermissionDeny: string
          // Workshop view
          WorkshopTitle: string
          Tools: string
          Agents: string
          Knowledge: string
          // Session view / components / dialogs / workshop actions
          ExecutionTraceLabel: string
          Download: string
          DownloadResult: string
          NoFilesOrTasks: string
          FilesAndTasks: string
          FilesWord: string
          TasksWord: string
          Cancel: string
          Submit: string
          Sending: string
          FeedbackPositiveHeader: string
          FeedbackNegativeHeader: string
          FeedbackPositivePrompt: string
          FeedbackNegativePrompt: string
          FeedbackCommentHint: string
          FeedbackCommentPlaceholder: string
          StartingServer: string
          PreparingRuntime: string
          ServerFailed: string
          Retry: string
          Discard: string
          Generate: string
          Delete: string
          GeneratedLabel: string
          AvailableTools: string
          AvailableAgents: string
          GenerateToolTitle: string
          GenerateToolHint: string
          GenerateAgentTitle: string
          GenerateAgentHint: string
          KnowledgeBase: string
          KnowledgeBaseIntro: string
          UploadFile: string }

    /// English (default) string table.
    let private en : Strings =
        { NewSessionTooltip = "New session"
          WorkshopTooltip = "Workshop"
          SettingsTooltip = "Settings"
          NoSessionSelected = "No session selected"
          ComposerPlaceholder = "Describe what to build..."
          Send = "Send"
          Attach = "Attach a file"
          StartConversation = "Start a conversation..."
          LoadingHistory = "Loading conversation history..."
          Working = "Working..."
          ThanksFeedback = "Thanks for your feedback"
          SettingsTitle = "Settings"
          SettingsSubtitle = "Configure the model provider, orchestrator and workspace."
          Appearance = "Appearance"
          Theme = "Theme"
          ThemeDark = "Dark"
          ThemeLight = "Light"
          Language = "Language"
          Provider = "Provider"
          Orchestrator = "Orchestrator"
          Workspace = "Workspace"
          Save = "Save"
          Close = "Close"
          LlmProvider = "LLM Provider"
          FieldType = "Type:"
          FieldEndpoint = "Endpoint:"
          FieldModel = "Model:"
          MaxRounds = "Max Rounds:"
          Temperature = "Temperature:"
          ContextWindow = "Window:"
          SystemPrompt = "System Prompt:"
          PathLabel = "Path:"
          WorkspaceWatermark = "Path to .nao workspace folder"
          WorkspaceHint = "Place an orchestrator.json in .nao/ folder to override orchestrator settings per workspace."
          Server = "Server"
          ServerMode = "Mode:"
          ServerLocal = "Local (embedded)"
          ServerRemote = "Remote (cloud)"
          ServerRemoteUrl = "Remote URL:"
          ServerEmail = "Email:"
          ServerSendLink = "Send verification link"
          ServerSignOut = "Sign out"
          ServerSignedInAs = "Signed in as"
          ServerNotSignedIn = "Not signed in"
          ServerHint = "Remote mode runs on Nao's server cluster for extra features and better performance. Sign in with a verification link sent to your email."
          Permissions = "Permissions"
          PermissionsEnabled = "Enforce access:"
          PermissionsOn = "On"
          PermissionsOff = "Off"
          PermissionsAllowedDomains = "Allowed web domains:"
          PermissionsAllowedPaths = "Allowed file paths:"
          PermissionsHint = "When enforcement is on, tools and agents may only reach the web domains and file paths listed here (one per line). Everything else is blocked. Files inside the session workspace are always allowed."
          PermissionPromptTitle = "Permission request"
          PermissionAllowOnce = "Allow once"
          PermissionAllowSession = "Allow this session"
          PermissionAllowGlobal = "Always allow"
          PermissionDeny = "Deny"
          WorkshopTitle = "Workshop"
          Tools = "Tools"
          Agents = "Agents"
          Knowledge = "Knowledge"
          ExecutionTraceLabel = "Execution trace"
          Download = "Download"
          DownloadResult = "Download result"
          NoFilesOrTasks = "No files in this session yet."
          FilesAndTasks = "Files"
          FilesWord = "files"
          TasksWord = "tasks"
          Cancel = "Cancel"
          Submit = "Submit"
          Sending = "Sending..."
          FeedbackPositiveHeader = "Positive feedback"
          FeedbackNegativeHeader = "Negative feedback"
          FeedbackPositivePrompt = "What did you like about this response?"
          FeedbackNegativePrompt = "What could have been better?"
          FeedbackCommentHint = "Optional \u2014 add a comment to explain your rating."
          FeedbackCommentPlaceholder = "Tell us more (optional)..."
          StartingServer = "Starting local server..."
          PreparingRuntime = "Preparing sessions and runtime"
          ServerFailed = "Server failed to start"
          Retry = "Retry"
          Discard = "Discard"
          Generate = "Generate"
          Delete = "Delete"
          GeneratedLabel = "Generated"
          AvailableTools = "Available tools"
          AvailableAgents = "Available agents"
          GenerateToolTitle = "Generate a tool from a requirement"
          GenerateToolHint = "e.g. Fetch the current weather for a city using a public API"
          GenerateAgentTitle = "Generate an agent (workflow) from a requirement"
          GenerateAgentHint = "e.g. A research assistant that searches files and summarizes findings"
          KnowledgeBase = "Knowledge base"
          KnowledgeBaseIntro = "Upload text files; their content is chunked, embedded and used to augment answers across all sessions."
          UploadFile = "Upload file" }

    /// Simplified Chinese string table.
    let private zh : Strings =
        { NewSessionTooltip = "新会话"
          WorkshopTooltip = "工坊"
          SettingsTooltip = "设置"
          NoSessionSelected = "未选择会话"
          ComposerPlaceholder = "描述你想构建的内容…"
          Send = "发送"
          Attach = "附加文件"
          StartConversation = "开始对话…"
          LoadingHistory = "正在加载对话历史…"
          Working = "处理中…"
          ThanksFeedback = "感谢您的反馈"
          SettingsTitle = "设置"
          SettingsSubtitle = "配置模型提供方、编排器和工作区。"
          Appearance = "外观"
          Theme = "主题"
          ThemeDark = "深色"
          ThemeLight = "浅色"
          Language = "语言"
          Provider = "提供方"
          Orchestrator = "编排器"
          Workspace = "工作区"
          Save = "保存"
          Close = "关闭"
          LlmProvider = "LLM 提供方"
          FieldType = "类型："
          FieldEndpoint = "端点："
          FieldModel = "模型："
          MaxRounds = "最大轮数："
          Temperature = "温度："
          ContextWindow = "上下文窗口："
          SystemPrompt = "系统提示词："
          PathLabel = "路径："
          WorkspaceWatermark = ".nao 工作区文件夹的路径"
          WorkspaceHint = "在 .nao/ 文件夹中放置 orchestrator.json 可按工作区覆盖编排器设置。"
          Server = "服务器"
          ServerMode = "模式："
          ServerLocal = "本地（内嵌）"
          ServerRemote = "远程（云端）"
          ServerRemoteUrl = "远程地址："
          ServerEmail = "邮箱："
          ServerSendLink = "发送验证链接"
          ServerSignOut = "退出登录"
          ServerSignedInAs = "已登录："
          ServerNotSignedIn = "未登录"
          ServerHint = "远程模式在 Nao 的服务器集群上运行，提供更多功能和更好的性能。使用发送到邮箱的验证链接登录。"
          Permissions = "权限"
          PermissionsEnabled = "启用访问控制："
          PermissionsOn = "开启"
          PermissionsOff = "关闭"
          PermissionsAllowedDomains = "允许的网站域名："
          PermissionsAllowedPaths = "允许的文件路径："
          PermissionsHint = "启用访问控制后，工具和智能体只能访问此处列出的网站域名和文件路径（每行一个），其他一律被拒绝。会话工作区内的文件始终允许访问。"
          PermissionPromptTitle = "权限请求"
          PermissionAllowOnce = "允许一次"
          PermissionAllowSession = "本会话允许"
          PermissionAllowGlobal = "始终允许"
          PermissionDeny = "拒绝"
          WorkshopTitle = "工坊"
          Tools = "工具"
          Agents = "智能体"
          Knowledge = "知识库"
          ExecutionTraceLabel = "执行轨迹"
          Download = "下载"
          DownloadResult = "下载结果"
          NoFilesOrTasks = "此会话中暂无文件。"
          FilesAndTasks = "文件"
          FilesWord = "个文件"
          TasksWord = "个任务"
          Cancel = "取消"
          Submit = "提交"
          Sending = "提交中…"
          FeedbackPositiveHeader = "好评反馈"
          FeedbackNegativeHeader = "差评反馈"
          FeedbackPositivePrompt = "你喜欢这条回复的哪些方面？"
          FeedbackNegativePrompt = "哪些方面可以改进？"
          FeedbackCommentHint = "可选 \u2014 添加评论以说明你的评分。"
          FeedbackCommentPlaceholder = "告诉我们更多（可选）…"
          StartingServer = "正在启动本地服务器…"
          PreparingRuntime = "正在准备会话和运行时"
          ServerFailed = "服务器启动失败"
          Retry = "重试"
          Discard = "放弃"
          Generate = "生成"
          Delete = "删除"
          GeneratedLabel = "已生成"
          AvailableTools = "可用工具"
          AvailableAgents = "可用智能体"
          GenerateToolTitle = "根据需求生成工具"
          GenerateToolHint = "例如：使用公共 API 获取某个城市的当前天气"
          GenerateAgentTitle = "根据需求生成智能体（工作流）"
          GenerateAgentHint = "例如：一个搜索文件并总结结果的研究助手"
          KnowledgeBase = "知识库"
          KnowledgeBaseIntro = "上传文本文件；其内容会被分块、嵌入，并用于在所有会话中增强回答。"
          UploadFile = "上传文件" }

    /// Hindi string table.
    let private hi : Strings =
        { NewSessionTooltip = "नया सत्र"
          WorkshopTooltip = "कार्यशाला"
          SettingsTooltip = "सेटिंग्स"
          NoSessionSelected = "कोई सत्र चयनित नहीं"
          ComposerPlaceholder = "बताएं क्या बनाना है…"
          Send = "भेजें"
          Attach = "फ़ाइल संलग्न करें"
          StartConversation = "बातचीत शुरू करें…"
          LoadingHistory = "बातचीत का इतिहास लोड हो रहा है…"
          Working = "काम चल रहा है…"
          ThanksFeedback = "आपकी प्रतिक्रिया के लिए धन्यवाद"
          SettingsTitle = "सेटिंग्स"
          SettingsSubtitle = "मॉडल प्रदाता, ऑर्केस्ट्रेटर और कार्यक्षेत्र कॉन्फ़िगर करें।"
          Appearance = "रूप"
          Theme = "थीम"
          ThemeDark = "गहरा"
          ThemeLight = "हल्का"
          Language = "भाषा"
          Provider = "प्रदाता"
          Orchestrator = "ऑर्केस्ट्रेटर"
          Workspace = "कार्यक्षेत्र"
          Save = "सहेजें"
          Close = "बंद करें"
          LlmProvider = "LLM प्रदाता"
          FieldType = "प्रकार:"
          FieldEndpoint = "एंडपॉइंट:"
          FieldModel = "मॉडल:"
          MaxRounds = "अधिकतम राउंड:"
          Temperature = "तापमान:"
          ContextWindow = "विंडो:"
          SystemPrompt = "सिस्टम प्रॉम्प्ट:"
          PathLabel = "पथ:"
          WorkspaceWatermark = ".nao कार्यक्षेत्र फ़ोल्डर का पथ"
          WorkspaceHint = "प्रति कार्यक्षेत्र ऑर्केस्ट्रेटर सेटिंग्स ओवरराइड करने के लिए .nao/ फ़ोल्डर में orchestrator.json रखें।"
          Server = "सर्वर"
          ServerMode = "मोड:"
          ServerLocal = "स्थानीय (एम्बेडेड)"
          ServerRemote = "रिमोट (क्लाउड)"
          ServerRemoteUrl = "रिमोट URL:"
          ServerEmail = "ईमेल:"
          ServerSendLink = "सत्यापन लिंक भेजें"
          ServerSignOut = "साइन आउट"
          ServerSignedInAs = "साइन इन के रूप में"
          ServerNotSignedIn = "साइन इन नहीं है"
          ServerHint = "रिमोट मोड अतिरिक्त सुविधाओं और बेहतर प्रदर्शन के लिए Nao के सर्वर क्लस्टर पर चलता है। अपने ईमेल पर भेजे गए सत्यापन लिंक से साइन इन करें।"
          Permissions = "अनुमतियाँ"
          PermissionsEnabled = "पहुँच लागू करें:"
          PermissionsOn = "चालू"
          PermissionsOff = "बंद"
          PermissionsAllowedDomains = "अनुमत वेब डोमेन:"
          PermissionsAllowedPaths = "अनुमत फ़ाइल पथ:"
          PermissionsHint = "जब लागू किया जाता है, तो उपकरण और एजेंट केवल यहाँ सूचीबद्ध वेब डोमेन और फ़ाइल पथ (प्रति पंक्ति एक) तक पहुँच सकते हैं। बाकी सब अवरुद्ध है। सत्र कार्यक्षेत्र के अंदर की फ़ाइलें हमेशा अनुमत हैं।"
          PermissionPromptTitle = "अनुमति अनुरोध"
          PermissionAllowOnce = "एक बार अनुमति दें"
          PermissionAllowSession = "इस सत्र के लिए अनुमति"
          PermissionAllowGlobal = "हमेशा अनुमति दें"
          PermissionDeny = "अस्वीकार करें"
          WorkshopTitle = "कार्यशाला"
          Tools = "उपकरण"
          Agents = "एजेंट"
          Knowledge = "ज्ञान"
          ExecutionTraceLabel = "निष्पादन ट्रेस"
          Download = "डाउनलोड"
          DownloadResult = "परिणाम डाउनलोड करें"
          NoFilesOrTasks = "इस सत्र में अभी कोई फ़ाइल नहीं है।"
          FilesAndTasks = "फ़ाइलें"
          FilesWord = "फ़ाइलें"
          TasksWord = "कार्य"
          Cancel = "रद्द करें"
          Submit = "सबमिट करें"
          Sending = "भेजा जा रहा है…"
          FeedbackPositiveHeader = "सकारात्मक प्रतिक्रिया"
          FeedbackNegativeHeader = "नकारात्मक प्रतिक्रिया"
          FeedbackPositivePrompt = "इस उत्तर में आपको क्या पसंद आया?"
          FeedbackNegativePrompt = "क्या बेहतर हो सकता था?"
          FeedbackCommentHint = "वैकल्पिक \u2014 अपनी रेटिंग समझाने के लिए टिप्पणी जोड़ें।"
          FeedbackCommentPlaceholder = "हमें और बताएं (वैकल्पिक)…"
          StartingServer = "स्थानीय सर्वर शुरू हो रहा है…"
          PreparingRuntime = "सत्र और रनटाइम तैयार किए जा रहे हैं"
          ServerFailed = "सर्वर शुरू होने में विफल"
          Retry = "पुनः प्रयास करें"
          Discard = "खारिज करें"
          Generate = "बनाएं"
          Delete = "हटाएं"
          GeneratedLabel = "जनरेट किया गया"
          AvailableTools = "उपलब्ध उपकरण"
          AvailableAgents = "उपलब्ध एजेंट"
          GenerateToolTitle = "आवश्यकता से एक उपकरण बनाएं"
          GenerateToolHint = "उदा. किसी सार्वजनिक API का उपयोग करके किसी शहर का वर्तमान मौसम प्राप्त करें"
          GenerateAgentTitle = "आवश्यकता से एक एजेंट (वर्कफ़्लो) बनाएं"
          GenerateAgentHint = "उदा. एक शोध सहायक जो फ़ाइलें खोजता है और निष्कर्षों का सारांश देता है"
          KnowledgeBase = "ज्ञान आधार"
          KnowledgeBaseIntro = "टेक्स्ट फ़ाइलें अपलोड करें; उनकी सामग्री को विभाजित, एम्बेड किया जाता है और सभी सत्रों में उत्तरों को बेहतर बनाने के लिए उपयोग किया जाता है।"
          UploadFile = "फ़ाइल अपलोड करें" }

    /// Spanish string table.
    let private es : Strings =
        { NewSessionTooltip = "Nueva sesión"
          WorkshopTooltip = "Taller"
          SettingsTooltip = "Configuración"
          NoSessionSelected = "Ninguna sesión seleccionada"
          ComposerPlaceholder = "Describe qué construir…"
          Send = "Enviar"
          Attach = "Adjuntar un archivo"
          StartConversation = "Inicia una conversación…"
          LoadingHistory = "Cargando el historial de conversación…"
          Working = "Trabajando…"
          ThanksFeedback = "Gracias por tus comentarios"
          SettingsTitle = "Configuración"
          SettingsSubtitle = "Configura el proveedor del modelo, el orquestador y el espacio de trabajo."
          Appearance = "Apariencia"
          Theme = "Tema"
          ThemeDark = "Oscuro"
          ThemeLight = "Claro"
          Language = "Idioma"
          Provider = "Proveedor"
          Orchestrator = "Orquestador"
          Workspace = "Espacio de trabajo"
          Save = "Guardar"
          Close = "Cerrar"
          LlmProvider = "Proveedor LLM"
          FieldType = "Tipo:"
          FieldEndpoint = "Endpoint:"
          FieldModel = "Modelo:"
          MaxRounds = "Rondas máximas:"
          Temperature = "Temperatura:"
          ContextWindow = "Ventana:"
          SystemPrompt = "Prompt del sistema:"
          PathLabel = "Ruta:"
          WorkspaceWatermark = "Ruta a la carpeta del espacio de trabajo .nao"
          WorkspaceHint = "Coloca un orchestrator.json en la carpeta .nao/ para anular la configuración del orquestador por espacio de trabajo."
          Server = "Servidor"
          ServerMode = "Modo:"
          ServerLocal = "Local (integrado)"
          ServerRemote = "Remoto (nube)"
          ServerRemoteUrl = "URL remota:"
          ServerEmail = "Correo:"
          ServerSendLink = "Enviar enlace de verificación"
          ServerSignOut = "Cerrar sesión"
          ServerSignedInAs = "Sesión iniciada como"
          ServerNotSignedIn = "Sin iniciar sesión"
          ServerHint = "El modo remoto se ejecuta en el clúster de servidores de Nao para más funciones y mejor rendimiento. Inicia sesión con un enlace de verificación enviado a tu correo."
          Permissions = "Permisos"
          PermissionsEnabled = "Aplicar acceso:"
          PermissionsOn = "Activado"
          PermissionsOff = "Desactivado"
          PermissionsAllowedDomains = "Dominios web permitidos:"
          PermissionsAllowedPaths = "Rutas de archivo permitidas:"
          PermissionsHint = "Cuando la aplicación está activada, las herramientas y los agentes solo pueden acceder a los dominios web y rutas de archivo enumerados aquí (uno por línea). Todo lo demás se bloquea. Los archivos dentro del espacio de trabajo de la sesión siempre están permitidos."
          PermissionPromptTitle = "Solicitud de permiso"
          PermissionAllowOnce = "Permitir una vez"
          PermissionAllowSession = "Permitir esta sesión"
          PermissionAllowGlobal = "Permitir siempre"
          PermissionDeny = "Denegar"
          WorkshopTitle = "Taller"
          Tools = "Herramientas"
          Agents = "Agentes"
          Knowledge = "Conocimiento"
          ExecutionTraceLabel = "Traza de ejecución"
          Download = "Descargar"
          DownloadResult = "Descargar resultado"
          NoFilesOrTasks = "Aún no hay archivos en esta sesión."
          FilesAndTasks = "Archivos"
          FilesWord = "archivos"
          TasksWord = "tareas"
          Cancel = "Cancelar"
          Submit = "Enviar"
          Sending = "Enviando…"
          FeedbackPositiveHeader = "Comentario positivo"
          FeedbackNegativeHeader = "Comentario negativo"
          FeedbackPositivePrompt = "¿Qué te gustó de esta respuesta?"
          FeedbackNegativePrompt = "¿Qué se podría mejorar?"
          FeedbackCommentHint = "Opcional \u2014 añade un comentario para explicar tu valoración."
          FeedbackCommentPlaceholder = "Cuéntanos más (opcional)…"
          StartingServer = "Iniciando el servidor local…"
          PreparingRuntime = "Preparando sesiones y entorno de ejecución"
          ServerFailed = "El servidor no pudo iniciarse"
          Retry = "Reintentar"
          Discard = "Descartar"
          Generate = "Generar"
          Delete = "Eliminar"
          GeneratedLabel = "Generado"
          AvailableTools = "Herramientas disponibles"
          AvailableAgents = "Agentes disponibles"
          GenerateToolTitle = "Generar una herramienta a partir de un requisito"
          GenerateToolHint = "p. ej. Obtener el clima actual de una ciudad usando una API pública"
          GenerateAgentTitle = "Generar un agente (flujo de trabajo) a partir de un requisito"
          GenerateAgentHint = "p. ej. Un asistente de investigación que busca archivos y resume hallazgos"
          KnowledgeBase = "Base de conocimiento"
          KnowledgeBaseIntro = "Sube archivos de texto; su contenido se divide, se incrusta y se usa para mejorar las respuestas en todas las sesiones."
          UploadFile = "Subir archivo" }

    /// French string table.
    let private fr : Strings =
        { NewSessionTooltip = "Nouvelle session"
          WorkshopTooltip = "Atelier"
          SettingsTooltip = "Paramètres"
          NoSessionSelected = "Aucune session sélectionnée"
          ComposerPlaceholder = "Décrivez ce qu'il faut créer…"
          Send = "Envoyer"
          Attach = "Joindre un fichier"
          StartConversation = "Démarrer une conversation…"
          LoadingHistory = "Chargement de l'historique de conversation…"
          Working = "En cours…"
          ThanksFeedback = "Merci pour votre retour"
          SettingsTitle = "Paramètres"
          SettingsSubtitle = "Configurez le fournisseur de modèle, l'orchestrateur et l'espace de travail."
          Appearance = "Apparence"
          Theme = "Thème"
          ThemeDark = "Sombre"
          ThemeLight = "Clair"
          Language = "Langue"
          Provider = "Fournisseur"
          Orchestrator = "Orchestrateur"
          Workspace = "Espace de travail"
          Save = "Enregistrer"
          Close = "Fermer"
          LlmProvider = "Fournisseur LLM"
          FieldType = "Type :"
          FieldEndpoint = "Point de terminaison :"
          FieldModel = "Modèle :"
          MaxRounds = "Tours maximum :"
          Temperature = "Température :"
          ContextWindow = "Fenêtre :"
          SystemPrompt = "Invite système :"
          PathLabel = "Chemin :"
          WorkspaceWatermark = "Chemin vers le dossier d'espace de travail .nao"
          WorkspaceHint = "Placez un orchestrator.json dans le dossier .nao/ pour remplacer les paramètres de l'orchestrateur par espace de travail."
          Server = "Serveur"
          ServerMode = "Mode :"
          ServerLocal = "Local (intégré)"
          ServerRemote = "Distant (cloud)"
          ServerRemoteUrl = "URL distante :"
          ServerEmail = "E-mail :"
          ServerSendLink = "Envoyer le lien de vérification"
          ServerSignOut = "Se déconnecter"
          ServerSignedInAs = "Connecté en tant que"
          ServerNotSignedIn = "Non connecté"
          ServerHint = "Le mode distant s'exécute sur le cluster de serveurs de Nao pour plus de fonctionnalités et de meilleures performances. Connectez-vous avec un lien de vérification envoyé à votre e-mail."
          Permissions = "Autorisations"
          PermissionsEnabled = "Appliquer l'accès :"
          PermissionsOn = "Activé"
          PermissionsOff = "Désactivé"
          PermissionsAllowedDomains = "Domaines web autorisés :"
          PermissionsAllowedPaths = "Chemins de fichiers autorisés :"
          PermissionsHint = "Lorsque l'application est activée, les outils et les agents ne peuvent accéder qu'aux domaines web et chemins de fichiers listés ici (un par ligne). Tout le reste est bloqué. Les fichiers dans l'espace de travail de la session sont toujours autorisés."
          PermissionPromptTitle = "Demande d'autorisation"
          PermissionAllowOnce = "Autoriser une fois"
          PermissionAllowSession = "Autoriser cette session"
          PermissionAllowGlobal = "Toujours autoriser"
          PermissionDeny = "Refuser"
          WorkshopTitle = "Atelier"
          Tools = "Outils"
          Agents = "Agents"
          Knowledge = "Connaissances"
          ExecutionTraceLabel = "Trace d'exécution"
          Download = "Télécharger"
          DownloadResult = "Télécharger le résultat"
          NoFilesOrTasks = "Aucun fichier dans cette session pour l'instant."
          FilesAndTasks = "Fichiers"
          FilesWord = "fichiers"
          TasksWord = "tâches"
          Cancel = "Annuler"
          Submit = "Envoyer"
          Sending = "Envoi…"
          FeedbackPositiveHeader = "Commentaire positif"
          FeedbackNegativeHeader = "Commentaire négatif"
          FeedbackPositivePrompt = "Qu'avez-vous aimé dans cette réponse ?"
          FeedbackNegativePrompt = "Qu'est-ce qui aurait pu être mieux ?"
          FeedbackCommentHint = "Facultatif \u2014 ajoutez un commentaire pour expliquer votre note."
          FeedbackCommentPlaceholder = "Dites-nous en plus (facultatif)…"
          StartingServer = "Démarrage du serveur local…"
          PreparingRuntime = "Préparation des sessions et du runtime"
          ServerFailed = "Le serveur n'a pas pu démarrer"
          Retry = "Réessayer"
          Discard = "Abandonner"
          Generate = "Générer"
          Delete = "Supprimer"
          GeneratedLabel = "Généré"
          AvailableTools = "Outils disponibles"
          AvailableAgents = "Agents disponibles"
          GenerateToolTitle = "Générer un outil à partir d'un besoin"
          GenerateToolHint = "p. ex. Récupérer la météo actuelle d'une ville via une API publique"
          GenerateAgentTitle = "Générer un agent (flux de travail) à partir d'un besoin"
          GenerateAgentHint = "p. ex. Un assistant de recherche qui parcourt des fichiers et résume les résultats"
          KnowledgeBase = "Base de connaissances"
          KnowledgeBaseIntro = "Téléchargez des fichiers texte ; leur contenu est découpé, vectorisé et utilisé pour enrichir les réponses dans toutes les sessions."
          UploadFile = "Téléverser un fichier" }

    /// Arabic string table.
    let private ar : Strings =
        { NewSessionTooltip = "جلسة جديدة"
          WorkshopTooltip = "الورشة"
          SettingsTooltip = "الإعدادات"
          NoSessionSelected = "لم يتم تحديد أي جلسة"
          ComposerPlaceholder = "صف ما تريد بناءه…"
          Send = "إرسال"
          Attach = "إرفاق ملف"
          StartConversation = "ابدأ محادثة…"
          LoadingHistory = "جارٍ تحميل سجل المحادثة…"
          Working = "جارٍ العمل…"
          ThanksFeedback = "شكرًا على ملاحظاتك"
          SettingsTitle = "الإعدادات"
          SettingsSubtitle = "قم بتكوين مزوّد النموذج والمنسّق ومساحة العمل."
          Appearance = "المظهر"
          Theme = "السمة"
          ThemeDark = "داكن"
          ThemeLight = "فاتح"
          Language = "اللغة"
          Provider = "المزوّد"
          Orchestrator = "المنسّق"
          Workspace = "مساحة العمل"
          Save = "حفظ"
          Close = "إغلاق"
          LlmProvider = "مزوّد LLM"
          FieldType = "النوع:"
          FieldEndpoint = "نقطة النهاية:"
          FieldModel = "النموذج:"
          MaxRounds = "الحد الأقصى للجولات:"
          Temperature = "درجة الحرارة:"
          ContextWindow = "النافذة:"
          SystemPrompt = "موجّه النظام:"
          PathLabel = "المسار:"
          WorkspaceWatermark = "المسار إلى مجلد مساحة عمل .nao"
          WorkspaceHint = "ضع ملف orchestrator.json في مجلد .nao/ لتجاوز إعدادات المنسّق لكل مساحة عمل."
          Server = "الخادم"
          ServerMode = "الوضع:"
          ServerLocal = "محلي (مضمّن)"
          ServerRemote = "بعيد (سحابي)"
          ServerRemoteUrl = "عنوان URL البعيد:"
          ServerEmail = "البريد الإلكتروني:"
          ServerSendLink = "إرسال رابط التحقق"
          ServerSignOut = "تسجيل الخروج"
          ServerSignedInAs = "تم تسجيل الدخول باسم"
          ServerNotSignedIn = "لم يتم تسجيل الدخول"
          ServerHint = "يعمل الوضع البعيد على مجموعة خوادم Nao لمزيد من الميزات وأداء أفضل. سجّل الدخول باستخدام رابط تحقق يُرسل إلى بريدك الإلكتروني."
          Permissions = "الأذونات"
          PermissionsEnabled = "فرض الوصول:"
          PermissionsOn = "تشغيل"
          PermissionsOff = "إيقاف"
          PermissionsAllowedDomains = "نطاقات الويب المسموح بها:"
          PermissionsAllowedPaths = "مسارات الملفات المسموح بها:"
          PermissionsHint = "عند تفعيل الفرض، لا يمكن للأدوات والوكلاء الوصول إلا إلى نطاقات الويب ومسارات الملفات المدرجة هنا (واحد في كل سطر). يُحظر كل ما عداها. الملفات داخل مساحة عمل الجلسة مسموح بها دائمًا."
          PermissionPromptTitle = "طلب إذن"
          PermissionAllowOnce = "السماح مرة واحدة"
          PermissionAllowSession = "السماح لهذه الجلسة"
          PermissionAllowGlobal = "السماح دائمًا"
          PermissionDeny = "رفض"
          WorkshopTitle = "الورشة"
          Tools = "الأدوات"
          Agents = "الوكلاء"
          Knowledge = "المعرفة"
          ExecutionTraceLabel = "أثر التنفيذ"
          Download = "تنزيل"
          DownloadResult = "تنزيل النتيجة"
          NoFilesOrTasks = "لا توجد ملفات في هذه الجلسة بعد."
          FilesAndTasks = "الملفات"
          FilesWord = "ملفات"
          TasksWord = "مهام"
          Cancel = "إلغاء"
          Submit = "إرسال"
          Sending = "جارٍ الإرسال…"
          FeedbackPositiveHeader = "ملاحظات إيجابية"
          FeedbackNegativeHeader = "ملاحظات سلبية"
          FeedbackPositivePrompt = "ما الذي أعجبك في هذا الرد؟"
          FeedbackNegativePrompt = "ما الذي كان يمكن تحسينه؟"
          FeedbackCommentHint = "اختياري \u2014 أضف تعليقًا لتوضيح تقييمك."
          FeedbackCommentPlaceholder = "أخبرنا المزيد (اختياري)…"
          StartingServer = "جارٍ تشغيل الخادم المحلي…"
          PreparingRuntime = "جارٍ تجهيز الجلسات وبيئة التشغيل"
          ServerFailed = "فشل تشغيل الخادم"
          Retry = "إعادة المحاولة"
          Discard = "تجاهل"
          Generate = "إنشاء"
          Delete = "حذف"
          GeneratedLabel = "تم الإنشاء"
          AvailableTools = "الأدوات المتاحة"
          AvailableAgents = "الوكلاء المتاحون"
          GenerateToolTitle = "إنشاء أداة من متطلب"
          GenerateToolHint = "مثال: جلب الطقس الحالي لمدينة باستخدام واجهة برمجة عامة"
          GenerateAgentTitle = "إنشاء وكيل (سير عمل) من متطلب"
          GenerateAgentHint = "مثال: مساعد بحثي يبحث في الملفات ويلخّص النتائج"
          KnowledgeBase = "قاعدة المعرفة"
          KnowledgeBaseIntro = "ارفع ملفات نصية؛ يتم تقسيم محتواها وتضمينه واستخدامه لتحسين الإجابات عبر جميع الجلسات."
          UploadFile = "رفع ملف" }

    /// Portuguese string table.
    let private pt : Strings =
        { NewSessionTooltip = "Nova sessão"
          WorkshopTooltip = "Oficina"
          SettingsTooltip = "Configurações"
          NoSessionSelected = "Nenhuma sessão selecionada"
          ComposerPlaceholder = "Descreva o que construir…"
          Send = "Enviar"
          Attach = "Anexar um arquivo"
          StartConversation = "Inicie uma conversa…"
          LoadingHistory = "Carregando o histórico da conversa…"
          Working = "Trabalhando…"
          ThanksFeedback = "Obrigado pelo seu feedback"
          SettingsTitle = "Configurações"
          SettingsSubtitle = "Configure o provedor do modelo, o orquestrador e o espaço de trabalho."
          Appearance = "Aparência"
          Theme = "Tema"
          ThemeDark = "Escuro"
          ThemeLight = "Claro"
          Language = "Idioma"
          Provider = "Provedor"
          Orchestrator = "Orquestrador"
          Workspace = "Espaço de trabalho"
          Save = "Salvar"
          Close = "Fechar"
          LlmProvider = "Provedor LLM"
          FieldType = "Tipo:"
          FieldEndpoint = "Endpoint:"
          FieldModel = "Modelo:"
          MaxRounds = "Máximo de rodadas:"
          Temperature = "Temperatura:"
          ContextWindow = "Janela:"
          SystemPrompt = "Prompt do sistema:"
          PathLabel = "Caminho:"
          WorkspaceWatermark = "Caminho para a pasta do espaço de trabalho .nao"
          WorkspaceHint = "Coloque um orchestrator.json na pasta .nao/ para substituir as configurações do orquestrador por espaço de trabalho."
          Server = "Servidor"
          ServerMode = "Modo:"
          ServerLocal = "Local (incorporado)"
          ServerRemote = "Remoto (nuvem)"
          ServerRemoteUrl = "URL remota:"
          ServerEmail = "E-mail:"
          ServerSendLink = "Enviar link de verificação"
          ServerSignOut = "Sair"
          ServerSignedInAs = "Conectado como"
          ServerNotSignedIn = "Não conectado"
          ServerHint = "O modo remoto é executado no cluster de servidores da Nao para mais recursos e melhor desempenho. Faça login com um link de verificação enviado para o seu e-mail."
          Permissions = "Permissões"
          PermissionsEnabled = "Aplicar acesso:"
          PermissionsOn = "Ligado"
          PermissionsOff = "Desligado"
          PermissionsAllowedDomains = "Domínios web permitidos:"
          PermissionsAllowedPaths = "Caminhos de arquivo permitidos:"
          PermissionsHint = "Quando a aplicação está ativada, ferramentas e agentes só podem acessar os domínios web e caminhos de arquivo listados aqui (um por linha). Todo o resto é bloqueado. Os arquivos dentro do espaço de trabalho da sessão são sempre permitidos."
          PermissionPromptTitle = "Solicitação de permissão"
          PermissionAllowOnce = "Permitir uma vez"
          PermissionAllowSession = "Permitir esta sessão"
          PermissionAllowGlobal = "Permitir sempre"
          PermissionDeny = "Negar"
          WorkshopTitle = "Oficina"
          Tools = "Ferramentas"
          Agents = "Agentes"
          Knowledge = "Conhecimento"
          ExecutionTraceLabel = "Rastreamento de execução"
          Download = "Baixar"
          DownloadResult = "Baixar resultado"
          NoFilesOrTasks = "Ainda não há arquivos nesta sessão."
          FilesAndTasks = "Arquivos"
          FilesWord = "arquivos"
          TasksWord = "tarefas"
          Cancel = "Cancelar"
          Submit = "Enviar"
          Sending = "Enviando…"
          FeedbackPositiveHeader = "Feedback positivo"
          FeedbackNegativeHeader = "Feedback negativo"
          FeedbackPositivePrompt = "Do que você gostou nesta resposta?"
          FeedbackNegativePrompt = "O que poderia ser melhor?"
          FeedbackCommentHint = "Opcional \u2014 adicione um comentário para explicar sua avaliação."
          FeedbackCommentPlaceholder = "Conte-nos mais (opcional)…"
          StartingServer = "Iniciando o servidor local…"
          PreparingRuntime = "Preparando sessões e ambiente de execução"
          ServerFailed = "Falha ao iniciar o servidor"
          Retry = "Tentar novamente"
          Discard = "Descartar"
          Generate = "Gerar"
          Delete = "Excluir"
          GeneratedLabel = "Gerado"
          AvailableTools = "Ferramentas disponíveis"
          AvailableAgents = "Agentes disponíveis"
          GenerateToolTitle = "Gerar uma ferramenta a partir de um requisito"
          GenerateToolHint = "ex.: Obter o clima atual de uma cidade usando uma API pública"
          GenerateAgentTitle = "Gerar um agente (fluxo de trabalho) a partir de um requisito"
          GenerateAgentHint = "ex.: Um assistente de pesquisa que busca arquivos e resume descobertas"
          KnowledgeBase = "Base de conhecimento"
          KnowledgeBaseIntro = "Envie arquivos de texto; o conteúdo é dividido, incorporado e usado para enriquecer as respostas em todas as sessões."
          UploadFile = "Enviar arquivo" }

    /// Russian string table.
    let private ru : Strings =
        { NewSessionTooltip = "Новая сессия"
          WorkshopTooltip = "Мастерская"
          SettingsTooltip = "Настройки"
          NoSessionSelected = "Сессия не выбрана"
          ComposerPlaceholder = "Опишите, что нужно создать…"
          Send = "Отправить"
          Attach = "Прикрепить файл"
          StartConversation = "Начните разговор…"
          LoadingHistory = "Загрузка истории разговора…"
          Working = "Выполняется…"
          ThanksFeedback = "Спасибо за ваш отзыв"
          SettingsTitle = "Настройки"
          SettingsSubtitle = "Настройте поставщика модели, оркестратор и рабочую область."
          Appearance = "Внешний вид"
          Theme = "Тема"
          ThemeDark = "Тёмная"
          ThemeLight = "Светлая"
          Language = "Язык"
          Provider = "Поставщик"
          Orchestrator = "Оркестратор"
          Workspace = "Рабочая область"
          Save = "Сохранить"
          Close = "Закрыть"
          LlmProvider = "Поставщик LLM"
          FieldType = "Тип:"
          FieldEndpoint = "Конечная точка:"
          FieldModel = "Модель:"
          MaxRounds = "Макс. раундов:"
          Temperature = "Температура:"
          ContextWindow = "Окно:"
          SystemPrompt = "Системный промпт:"
          PathLabel = "Путь:"
          WorkspaceWatermark = "Путь к папке рабочей области .nao"
          WorkspaceHint = "Поместите orchestrator.json в папку .nao/, чтобы переопределить настройки оркестратора для рабочей области."
          Server = "Сервер"
          ServerMode = "Режим:"
          ServerLocal = "Локальный (встроенный)"
          ServerRemote = "Удалённый (облако)"
          ServerRemoteUrl = "Удалённый URL:"
          ServerEmail = "Эл. почта:"
          ServerSendLink = "Отправить ссылку для подтверждения"
          ServerSignOut = "Выйти"
          ServerSignedInAs = "Вы вошли как"
          ServerNotSignedIn = "Вход не выполнен"
          ServerHint = "Удалённый режим работает на серверном кластере Nao для дополнительных функций и более высокой производительности. Войдите по ссылке подтверждения, отправленной на вашу почту."
          Permissions = "Разрешения"
          PermissionsEnabled = "Контроль доступа:"
          PermissionsOn = "Вкл"
          PermissionsOff = "Выкл"
          PermissionsAllowedDomains = "Разрешённые веб-домены:"
          PermissionsAllowedPaths = "Разрешённые пути к файлам:"
          PermissionsHint = "Когда контроль включён, инструменты и агенты могут обращаться только к перечисленным здесь веб-доменам и путям к файлам (по одному в строке). Всё остальное блокируется. Файлы внутри рабочей области сессии всегда разрешены."
          PermissionPromptTitle = "Запрос разрешения"
          PermissionAllowOnce = "Разрешить однажды"
          PermissionAllowSession = "Разрешить в этой сессии"
          PermissionAllowGlobal = "Разрешать всегда"
          PermissionDeny = "Отклонить"
          WorkshopTitle = "Мастерская"
          Tools = "Инструменты"
          Agents = "Агенты"
          Knowledge = "Знания"
          ExecutionTraceLabel = "Трассировка выполнения"
          Download = "Скачать"
          DownloadResult = "Скачать результат"
          NoFilesOrTasks = "В этой сессии пока нет файлов."
          FilesAndTasks = "Файлы"
          FilesWord = "файлов"
          TasksWord = "задач"
          Cancel = "Отмена"
          Submit = "Отправить"
          Sending = "Отправка…"
          FeedbackPositiveHeader = "Положительный отзыв"
          FeedbackNegativeHeader = "Отрицательный отзыв"
          FeedbackPositivePrompt = "Что вам понравилось в этом ответе?"
          FeedbackNegativePrompt = "Что можно было бы улучшить?"
          FeedbackCommentHint = "Необязательно \u2014 добавьте комментарий, чтобы пояснить свою оценку."
          FeedbackCommentPlaceholder = "Расскажите подробнее (необязательно)…"
          StartingServer = "Запуск локального сервера…"
          PreparingRuntime = "Подготовка сессий и среды выполнения"
          ServerFailed = "Не удалось запустить сервер"
          Retry = "Повторить"
          Discard = "Отменить"
          Generate = "Сгенерировать"
          Delete = "Удалить"
          GeneratedLabel = "Сгенерировано"
          AvailableTools = "Доступные инструменты"
          AvailableAgents = "Доступные агенты"
          GenerateToolTitle = "Создать инструмент по требованию"
          GenerateToolHint = "напр. Получить текущую погоду города через публичный API"
          GenerateAgentTitle = "Создать агента (рабочий процесс) по требованию"
          GenerateAgentHint = "напр. Исследовательский помощник, который ищет файлы и обобщает результаты"
          KnowledgeBase = "База знаний"
          KnowledgeBaseIntro = "Загрузите текстовые файлы; их содержимое разбивается, векторизуется и используется для улучшения ответов во всех сессиях."
          UploadFile = "Загрузить файл" }

    /// Japanese string table.
    let private ja : Strings =
        { NewSessionTooltip = "新しいセッション"
          WorkshopTooltip = "ワークショップ"
          SettingsTooltip = "設定"
          NoSessionSelected = "セッションが選択されていません"
          ComposerPlaceholder = "作りたいものを説明してください…"
          Send = "送信"
          Attach = "ファイルを添付"
          StartConversation = "会話を始めましょう…"
          LoadingHistory = "会話履歴を読み込んでいます…"
          Working = "処理中…"
          ThanksFeedback = "フィードバックありがとうございます"
          SettingsTitle = "設定"
          SettingsSubtitle = "モデルプロバイダー、オーケストレーター、ワークスペースを設定します。"
          Appearance = "外観"
          Theme = "テーマ"
          ThemeDark = "ダーク"
          ThemeLight = "ライト"
          Language = "言語"
          Provider = "プロバイダー"
          Orchestrator = "オーケストレーター"
          Workspace = "ワークスペース"
          Save = "保存"
          Close = "閉じる"
          LlmProvider = "LLM プロバイダー"
          FieldType = "種類:"
          FieldEndpoint = "エンドポイント:"
          FieldModel = "モデル:"
          MaxRounds = "最大ラウンド数:"
          Temperature = "温度:"
          ContextWindow = "ウィンドウ:"
          SystemPrompt = "システムプロンプト:"
          PathLabel = "パス:"
          WorkspaceWatermark = ".nao ワークスペースフォルダーへのパス"
          WorkspaceHint = ".nao/ フォルダーに orchestrator.json を置くと、ワークスペースごとにオーケストレーター設定を上書きできます。"
          Server = "サーバー"
          ServerMode = "モード:"
          ServerLocal = "ローカル（組み込み）"
          ServerRemote = "リモート（クラウド）"
          ServerRemoteUrl = "リモート URL:"
          ServerEmail = "メール:"
          ServerSendLink = "確認リンクを送信"
          ServerSignOut = "サインアウト"
          ServerSignedInAs = "サインイン中:"
          ServerNotSignedIn = "サインインしていません"
          ServerHint = "リモートモードは Nao のサーバークラスター上で動作し、追加機能と高いパフォーマンスを提供します。メールに送信される確認リンクでサインインしてください。"
          Permissions = "権限"
          PermissionsEnabled = "アクセス制御："
          PermissionsOn = "オン"
          PermissionsOff = "オフ"
          PermissionsAllowedDomains = "許可するウェブドメイン："
          PermissionsAllowedPaths = "許可するファイルパス："
          PermissionsHint = "制御が有効な場合、ツールとエージェントはここに記載されたウェブドメインとファイルパス（1行に1つ）にのみアクセスできます。それ以外はすべてブロックされます。セッションワークスペース内のファイルは常に許可されます。"
          PermissionPromptTitle = "権限リクエスト"
          PermissionAllowOnce = "今回のみ許可"
          PermissionAllowSession = "このセッションで許可"
          PermissionAllowGlobal = "常に許可"
          PermissionDeny = "拒否"
          WorkshopTitle = "ワークショップ"
          Tools = "ツール"
          Agents = "エージェント"
          Knowledge = "ナレッジ"
          ExecutionTraceLabel = "実行トレース"
          Download = "ダウンロード"
          DownloadResult = "結果をダウンロード"
          NoFilesOrTasks = "このセッションにはまだファイルがありません。"
          FilesAndTasks = "ファイル"
          FilesWord = "ファイル"
          TasksWord = "タスク"
          Cancel = "キャンセル"
          Submit = "送信"
          Sending = "送信中…"
          FeedbackPositiveHeader = "高評価のフィードバック"
          FeedbackNegativeHeader = "低評価のフィードバック"
          FeedbackPositivePrompt = "この回答のどこが良かったですか？"
          FeedbackNegativePrompt = "どこを改善できますか？"
          FeedbackCommentHint = "任意 \u2014 評価の理由をコメントで追加してください。"
          FeedbackCommentPlaceholder = "詳しく教えてください（任意）…"
          StartingServer = "ローカルサーバーを起動しています…"
          PreparingRuntime = "セッションとランタイムを準備しています"
          ServerFailed = "サーバーの起動に失敗しました"
          Retry = "再試行"
          Discard = "破棄"
          Generate = "生成"
          Delete = "削除"
          GeneratedLabel = "生成済み"
          AvailableTools = "利用可能なツール"
          AvailableAgents = "利用可能なエージェント"
          GenerateToolTitle = "要件からツールを生成"
          GenerateToolHint = "例：公開 API を使って都市の現在の天気を取得する"
          GenerateAgentTitle = "要件からエージェント（ワークフロー）を生成"
          GenerateAgentHint = "例：ファイルを検索して結果を要約するリサーチアシスタント"
          KnowledgeBase = "ナレッジベース"
          KnowledgeBaseIntro = "テキストファイルをアップロードすると、その内容はチャンク化・埋め込みされ、すべてのセッションで回答の強化に使用されます。"
          UploadFile = "ファイルをアップロード" }

    /// German string table.
    let private de : Strings =
        { NewSessionTooltip = "Neue Sitzung"
          WorkshopTooltip = "Werkstatt"
          SettingsTooltip = "Einstellungen"
          NoSessionSelected = "Keine Sitzung ausgewählt"
          ComposerPlaceholder = "Beschreibe, was erstellt werden soll…"
          Send = "Senden"
          Attach = "Datei anhängen"
          StartConversation = "Starte eine Unterhaltung…"
          LoadingHistory = "Unterhaltungsverlauf wird geladen…"
          Working = "Wird bearbeitet…"
          ThanksFeedback = "Danke für dein Feedback"
          SettingsTitle = "Einstellungen"
          SettingsSubtitle = "Konfiguriere den Modellanbieter, den Orchestrator und den Arbeitsbereich."
          Appearance = "Erscheinungsbild"
          Theme = "Design"
          ThemeDark = "Dunkel"
          ThemeLight = "Hell"
          Language = "Sprache"
          Provider = "Anbieter"
          Orchestrator = "Orchestrator"
          Workspace = "Arbeitsbereich"
          Save = "Speichern"
          Close = "Schließen"
          LlmProvider = "LLM-Anbieter"
          FieldType = "Typ:"
          FieldEndpoint = "Endpunkt:"
          FieldModel = "Modell:"
          MaxRounds = "Maximale Runden:"
          Temperature = "Temperatur:"
          ContextWindow = "Fenster:"
          SystemPrompt = "System-Prompt:"
          PathLabel = "Pfad:"
          WorkspaceWatermark = "Pfad zum .nao-Arbeitsbereichsordner"
          WorkspaceHint = "Lege eine orchestrator.json im .nao/-Ordner ab, um die Orchestrator-Einstellungen pro Arbeitsbereich zu überschreiben."
          Server = "Server"
          ServerMode = "Modus:"
          ServerLocal = "Lokal (eingebettet)"
          ServerRemote = "Remote (Cloud)"
          ServerRemoteUrl = "Remote-URL:"
          ServerEmail = "E-Mail:"
          ServerSendLink = "Bestätigungslink senden"
          ServerSignOut = "Abmelden"
          ServerSignedInAs = "Angemeldet als"
          ServerNotSignedIn = "Nicht angemeldet"
          ServerHint = "Der Remote-Modus läuft auf dem Servercluster von Nao für zusätzliche Funktionen und bessere Leistung. Melden Sie sich mit einem Bestätigungslink an, der an Ihre E-Mail gesendet wird."
          Permissions = "Berechtigungen"
          PermissionsEnabled = "Zugriff erzwingen:"
          PermissionsOn = "Ein"
          PermissionsOff = "Aus"
          PermissionsAllowedDomains = "Erlaubte Web-Domains:"
          PermissionsAllowedPaths = "Erlaubte Dateipfade:"
          PermissionsHint = "Wenn die Erzwingung aktiviert ist, können Tools und Agenten nur auf die hier aufgeführten Web-Domains und Dateipfade (eine pro Zeile) zugreifen. Alles andere wird blockiert. Dateien im Sitzungsarbeitsbereich sind immer erlaubt."
          PermissionPromptTitle = "Berechtigungsanfrage"
          PermissionAllowOnce = "Einmal erlauben"
          PermissionAllowSession = "Diese Sitzung erlauben"
          PermissionAllowGlobal = "Immer erlauben"
          PermissionDeny = "Ablehnen"
          WorkshopTitle = "Werkstatt"
          Tools = "Werkzeuge"
          Agents = "Agenten"
          Knowledge = "Wissen"
          ExecutionTraceLabel = "Ausführungsverlauf"
          Download = "Herunterladen"
          DownloadResult = "Ergebnis herunterladen"
          NoFilesOrTasks = "Noch keine Dateien in dieser Sitzung."
          FilesAndTasks = "Dateien"
          FilesWord = "Dateien"
          TasksWord = "Aufgaben"
          Cancel = "Abbrechen"
          Submit = "Senden"
          Sending = "Wird gesendet…"
          FeedbackPositiveHeader = "Positives Feedback"
          FeedbackNegativeHeader = "Negatives Feedback"
          FeedbackPositivePrompt = "Was hat Ihnen an dieser Antwort gefallen?"
          FeedbackNegativePrompt = "Was hätte besser sein können?"
          FeedbackCommentHint = "Optional \u2014 fügen Sie einen Kommentar hinzu, um Ihre Bewertung zu erklären."
          FeedbackCommentPlaceholder = "Erzählen Sie uns mehr (optional)…"
          StartingServer = "Lokaler Server wird gestartet…"
          PreparingRuntime = "Sitzungen und Laufzeit werden vorbereitet"
          ServerFailed = "Server konnte nicht gestartet werden"
          Retry = "Erneut versuchen"
          Discard = "Verwerfen"
          Generate = "Generieren"
          Delete = "Löschen"
          GeneratedLabel = "Generiert"
          AvailableTools = "Verfügbare Werkzeuge"
          AvailableAgents = "Verfügbare Agenten"
          GenerateToolTitle = "Ein Werkzeug aus einer Anforderung generieren"
          GenerateToolHint = "z. B. Das aktuelle Wetter einer Stadt über eine öffentliche API abrufen"
          GenerateAgentTitle = "Einen Agenten (Workflow) aus einer Anforderung generieren"
          GenerateAgentHint = "z. B. Ein Rechercheassistent, der Dateien durchsucht und Ergebnisse zusammenfasst"
          KnowledgeBase = "Wissensdatenbank"
          KnowledgeBaseIntro = "Laden Sie Textdateien hoch; ihr Inhalt wird in Abschnitte zerlegt, eingebettet und zur Verbesserung der Antworten in allen Sitzungen verwendet."
          UploadFile = "Datei hochladen" }

    let private tableFor (lang: Language) : Strings =
        match lang with
        | English -> en
        | Chinese -> zh
        | Hindi -> hi
        | Spanish -> es
        | French -> fr
        | Arabic -> ar
        | Portuguese -> pt
        | Russian -> ru
        | Japanese -> ja
        | German -> de

    /// The active language. Switched from settings; read fresh on each render.
    let mutable currentLanguage = English

    /// The active string table.
    let current () : Strings = tableFor currentLanguage

    /// All selectable languages, in display order.
    let all : Language list =
        [ English; Chinese; Hindi; Spanish; French; Arabic; Portuguese; Russian; Japanese; German ]

    /// Human-readable name of a language (in its own language).
    let displayName (lang: Language) : string =
        match lang with
        | English -> "English"
        | Chinese -> "简体中文"
        | Hindi -> "हिन्दी"
        | Spanish -> "Español"
        | French -> "Français"
        | Arabic -> "العربية"
        | Portuguese -> "Português"
        | Russian -> "Русский"
        | Japanese -> "日本語"
        | German -> "Deutsch"

    /// Persistable code for a language.
    let code (lang: Language) : string =
        match lang with
        | English -> "en"
        | Chinese -> "zh"
        | Hindi -> "hi"
        | Spanish -> "es"
        | French -> "fr"
        | Arabic -> "ar"
        | Portuguese -> "pt"
        | Russian -> "ru"
        | Japanese -> "ja"
        | German -> "de"

    /// Parse a persisted language code, defaulting to English.
    let parse (value: string) : Language =
        match (if isNull value then "" else value).Trim().ToLowerInvariant() with
        | "en" | "english" | "" -> English
        | "zh" | "zh-cn" | "zh-hans" | "chinese" -> Chinese
        | "hi" | "hindi" -> Hindi
        | "es" | "spanish" | "español" -> Spanish
        | "fr" | "french" | "français" -> French
        | "ar" | "arabic" -> Arabic
        | "pt" | "pt-br" | "portuguese" | "português" -> Portuguese
        | "ru" | "russian" -> Russian
        | "ja" | "jp" | "japanese" -> Japanese
        | "de" | "german" | "deutsch" -> German
        | _ -> English

    /// Switch the active language.
    let apply (lang: Language) = currentLanguage <- lang
