<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Nao.Providers\src\Configs\OllamaConfig.fs" Link="src\Configs\OllamaConfig.fs" />
    <Compile Include="..\Nao.Providers\src\Providers\OllamaProvider.fs" Link="src\Providers\OllamaProvider.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nao.Agents\Nao.Agents.fsproj" />
    <ProjectReference Include="..\Nao.Providers.OpenAICompatible\Nao.Providers.OpenAICompatible.fsproj" />
  </ItemGroup>

  <Import Project="..\..\.paket\Paket.Restore.targets" />

</Project>
